# Generated by Django 5.2 on 2025-04-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('from_emotion', models.CharField(max_length=50)),
                ('to_emotion', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=0)),
                ('initial_mood_rating', models.IntegerField(null=True)),
                ('final_mood_rating', models.IntegerField(null=True)),
                ('earned_medal', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emotionalcourse')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
